services:
  customer-db:
    image: postgres
    container_name: minibank-customer-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: customer
  account-db:
    image: postgres
    container_name: minibank-account-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: account
  transfer-db:
    image: postgres
    container_name: minibank-transfer-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: transfer
  inquiry-db:
    image: mongo
    container_name: minibank-inquiry-db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin1234
  minibank-kafka:
    image: apache/kafka
    hostname: minibank-kafka
    container_name: minibank-kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'CONTROLLER://:9093,EXTERNAL://:9092,PLAINTEXT://:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:9092,PLAINTEXT://minibank-kafka:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      # Controller
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@minibank-kafka:9093'
      # Broker
      KAFKA_NODE_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  minibank-kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: minibank-kafka-ui
    ports:
      - '8099:8080'
    depends_on:
      - minibank-kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: minibank-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: minibank-kafka:9094
      KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: true
      KAFKA_CLUSTERS_0_CONSOLEAUDITENABLED: true
      DYNAMIC_CONFIG_ENABLED: true