server:
  port: 9076
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin1234
    url: jdbc:postgresql://localhost:5432/customer
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
    filter: true
    operations-sorter: alpha