server:
  port: 80
spring:
  application:
    name: minibank-gateway
  cloud:
    gateway:
      routes:
        - id: minibank-account
          uri: lb://minibank-account
          predicates:
            - Path=/minibank/account/**
        - id: minibank-customer
          uri: lb://minibank-customer
          predicates:
            - Path=/minibank/customer/**
        - id: minibank-transfer
          uri: lb://minibank-transfer
          predicates:
            - Path=/minibank/transfer/**
        - id: minibank-inquiry
          uri: lb://minibank-inquiry
          predicates:
            - Path=/minibank/inquiry/**